config/routes.rb
PhlogBlog::Application.routes.draw do
  resources :photos

  root to: "photos#index"

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :picture, PictureUploader

  after_save :enqueue_picture

  def picture_name
    File.basename(picture.path || picture.filename) if picture
  end

  def enqueue_picture
    ImageWorker.perform_async(id, key) if key.present?
  end

  class ImageWorker
    include Sidekiq::Worker

    def perform(id, key)
      photo = Photo.find(id)
      photo.key = key
      photo.remote_picture_url = photo.picture.direct_fog_url(with_path: true)
      photo.save!
      photo.update_column(:picture_processed, true)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_filter lambda{ request.body.rewind }

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @photos = Photo.all
    @uploader = Photo.new.picture
    @uploader.success_action_redirect = new_photo_url
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new(key: params[:key])
  end

  # GET /photos/1/edit
  def edit
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @photo }
      else
        format.html { render action: 'new' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:name, :picture, :key)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Phlogger</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <div class="brand">Phlogger</div>
      <div class="nav-collapse">
        <ul class="nav">
          <li><%= link_to "All Photos", photos_path %></li>
        </ul>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <%= yield %>
</div>

<footer>
  <div class="container">
    Stephanie Datu | 2013
  </div>
</footer>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_for @photo, html: { class: 'form-horizontal' } do |f| %>
<%= f.hidden_field :key %>

<p>File: <%= @photo.picture_name %></p>

  <div class="control-group">
    <%= f.label :name, class: 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, class: 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, class: 'btn btn-primary' %>
    <%= link_to t('.cancel', default: t("helpers.links.cancel")),
                photos_path, class: 'btn' %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<%- model_class = Photo -%>
<div class="page-header">
  <h1><%=t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

app/views/photos/index.html.erb
<%- model_class = Photo -%>
<div class="page-header">
  <h1><%=t '.title', default: model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table">
  <thead>
    <tr>
    </tr>
  </thead>
  <tbody>
    <% @photos.each do |photo| %>
      <tr>
        <div class="row" >
          <div class="col-md-4">
            <p><strong><%= photo.name %></strong></p>
            <p><%=l photo.created_at, format: :short %></p>
            <% if photo.picture_processed? %>
              <p><%= link_to image_tag(photo.picture_url(:thumb)), photo_path(photo) %></p>
            <% else %>
              <em>Processing...</em>
            <% end %>
            <p><%= link_to t('.edit', default: t("helpers.links.edit")),
                        edit_photo_path(photo), class: 'btn btn-mini' %>
            <%= link_to t('.destroy', default: t("helpers.links.destroy")),
                        photo_path(photo),
                        method: :delete,
                        data: { confirm: t('.confirm',
                                default: t("helpers.links.confirm",
                                default: 'Are you sure?')) },
                                class: 'btn btn-mini btn-danger' %></p>
          </div>
        </div>
      </tr>
    <% end %>
  </tbody>
</table>

<%= direct_upload_form_for @uploader do |f| %>
  <p><%= f.file_field :picture %></p>
  <p><%= f.submit "Upload Picture" %></p>
<% end %>

app/views/photos/new.html.erb
<%- model_class = Photo -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

app/views/photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @photo.name %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@photo.picture_url) if @photo.picture.present? %>
</p>

<%= link_to 'Edit', edit_photo_path(@photo) %> |
<%= link_to 'Back', photos_path %>